/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _OP_H_RPCGEN
#define _OP_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct inputs {
	struct {
		u_int num_len;
		double *num_val;
	} num;
	int num_size;
};
typedef struct inputs inputs;

#define OP_PROG 2345611111
#define OP_VERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define SUM 1
extern  double * sum_1(inputs *, CLIENT *);
extern  double * sum_1_svc(inputs *, struct svc_req *);
#define MAXI 2
extern  double * maxi_1(inputs *, CLIENT *);
extern  double * maxi_1_svc(inputs *, struct svc_req *);
#define MINI 3
extern  double * mini_1(inputs *, CLIENT *);
extern  double * mini_1_svc(inputs *, struct svc_req *);
extern int op_prog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define SUM 1
extern  double * sum_1();
extern  double * sum_1_svc();
#define MAXI 2
extern  double * maxi_1();
extern  double * maxi_1_svc();
#define MINI 3
extern  double * mini_1();
extern  double * mini_1_svc();
extern int op_prog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_inputs (XDR *, inputs*);

#else /* K&R C */
extern bool_t xdr_inputs ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_OP_H_RPCGEN */
