/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "op.h"
#include<ctype.h>
#include<string.h>
#include<stdlib.h>

void
op_prog_1(char *host, char *request, int n, double input[])
{
	CLIENT *clnt;
	double  *result_1;
	inputs  sum_1_arg;
	double  *result_2;
	inputs  maxi_1_arg;
	double  *result_3;
	inputs  mini_1_arg;

#ifndef	DEBUG
	clnt = clnt_create (host, OP_PROG, OP_VERS, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */
	char *r = request;
	char req_type[3];
	//printf("%s\n", r);
	int k=0;
	while(*r){
		*r = toupper((unsigned char) *r);
		req_type[k] = *r;
		k+=1;
    		r+=1;
	}

	int i;

	//printf("%s\n", request);
	//printf("%s\n", req_type);
	// If user wants to calculate sum of array elements

	if(strcmp(req_type, "SUM") == 0){
		
		// storing number of array elements in the structure variables
		sum_1_arg.num.num_len=n;
		sum_1_arg.num_size=n;
		// allocating space in the memory
		sum_1_arg.num.num_val=(double *) malloc(n*sizeof(double));
		
		
		printf("\n");
		// Storing values in the structure variable
		for(i=0;i<n;i++)
		{
			
			sum_1_arg.num.num_val[i] = input[i];
			
		}
		
		result_1 = sum_1(&sum_1_arg, clnt);
		
		if (result_1 == (double *) NULL) 
		{
			clnt_perror (clnt, "call failed");
		}
		else
		{
			printf("\n");
			printf("sum of numbers is %.2f\n", *result_1);
			printf("\n");
		}
	}
	// If user wants to compute maximum of array elements

	else if(strcmp(req_type, "MAX")== 0){
	
	
		// storing number of array elements in the structure variables
		maxi_1_arg.num.num_len=n;
		maxi_1_arg.num_size=n;
		// allocating space in the memory
		maxi_1_arg.num.num_val=(double *) malloc(n*sizeof(double));
		
		printf("\n");
		// Storing values in the structure variable
		for(i=0;i<n;i++)
		{
			
			maxi_1_arg.num.num_val[i] = input[i];
				
		}
		// passing input variable to the max function and storing answer in result_2
		result_2 = maxi_1(&maxi_1_arg, clnt);
		
		if (result_2 == (double *) NULL) 
		{
			clnt_perror (clnt, "call failed");
		}
		else
		{
			printf("\n");
			printf("Maximum of numbers is %.2f\n", *result_2);
			printf("\n");
		}
	}
	// If user wants to compute minimum of array elements

	else if(strcmp(req_type, "MIN") == 0)
	{
		
		
	
		printf("\n");
		// storing number of array elements in the structure variables
		mini_1_arg.num.num_len=n;
		mini_1_arg.num_size=n;
		// allocating space in the memory 
		mini_1_arg.num.num_val=(double *) malloc(n*sizeof(double));
		// Storing values in the structure variable
		for(i=0;i<n;i++)
		{
			
			mini_1_arg.num.num_val[i] = input[i];
				
		}
		
		
		
		printf("\n");
		// passing input variable to the min function and storing answer in result_3
		result_3 = mini_1(&mini_1_arg, clnt);
		
		if (result_3 == (double *) NULL) 
		{
			clnt_perror (clnt, "call failed");
		}
		else
		{
			printf("\n");
			printf("Minimum of numbers is %.2f\n", *result_3);
			printf("\n");
		}
		
	}
	
	else{
		printf("The request name is invalid. (Enter SUM, MAX or MIN)\n");
	}
	
	
	
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}
	



int
main (int argc, char *argv[])
{
	// creating pointer variable for localhost
	char *host;

	// creating request variable for request_type
	char *req;
	
	if (argc < 3) {
		printf ("usage: %s server_host request_type array_elements\n", argv[0]);
		exit (1);
	}
	// n stores the value for number of array elements
	int n = argc - 3;
	
	double numbers[n];
	// argv[1] is a char pointer pointing to localhost (As per question) and assigning it to host 
	host = argv[1];

	// argv[2] is a char pointer pointing to request_type (As per question) and assigning it to req
	req = argv[2];
	int j=0;
	// Storing the element arguments in numbers array
	for(int i=3; i<argc; i++){
		numbers[j] = atof(argv[i]); 
		j++;
	}
	
	// If user doensn't type "localhost"
	if(strcmp(host, "localhost")!=0){
		printf ("Enter appropriate hostname!\n");
		exit(1);
	}
	// If user doesn't enter any elements
	if(n == 0){
		printf("Number list is empty. Please enter some inputs.\n");
		exit(1);
	}
	// Passing all the command line arguments into op_prog_1 function		
	op_prog_1 (host, req, n, numbers);
exit (0);
}
