/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "op.h"

bool_t
xdr_inputs (XDR *xdrs, inputs *objp)
{
	register int32_t *buf;

	 if (!xdr_array (xdrs, (char **)&objp->num.num_val, (u_int *) &objp->num.num_len, 100,
		sizeof (double), (xdrproc_t) xdr_double))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->num_size))
		 return FALSE;
	return TRUE;
}
